CREATE TABLE ROUNDS
    (
        RND_ID NUMBER(4) CONSTRAINT RND_ID_PK PRIMARY KEY,
        RND_NAME VARCHAR2(50),
        RND_START_DATE DATE,
        RND_END_DATE DATE,
        RND_PRICE NUMBER(8,2),
        CRS_ID NUMBER(4)
    );
    
CREATE TABLE COURSES
    (
        CRS_ID NUMBER(4) CONSTRAINT CRS_ID_PK PRIMARY KEY,
        CRS_NAME VARCHAR2(50),
        CRS_HOURS NUMBER(3),
        CRS_PRICE NUMBER(8,2),
        RND_DAYS VARCHAR2(50)
    );

CREATE TABLE STUDENTS
    (
        ST_ID NUMBER(4) CONSTRAINT ST_ID_PK PRIMARY KEY,
        ST_NAME VARCHAR2(50),
        ST_MOBILE VARCHAR2(11) CONSTRAINT MOB_U UNIQUE,
        ST_ADDRESS VARCHAR2(50)
    );
    
CREATE TABLE STUDENTS_ROUNDS
    (
        ID NUMBER(4) CONSTRAINT SR_ID_PK PRIMARY KEY,
        ST_ID NUMBER(4),
        RND_ID NUMBER(4),
        PAID_AMOUNT NUMBER(8,2)
    );
    
INSERT INTO STUDENTS
    (ST_ID, ST_NAME, ST_MOBILE, ST_ADDRESS)
VALUES
    (1, 'Mostafa Medhat', '01235894324', '111 AFKG');
INSERT INTO STUDENTS
    (ST_ID, ST_NAME, ST_MOBILE, ST_ADDRESS)
VALUES
    (2, 'Ahmed Awad', '01009884738', '394 JKSL');
INSERT INTO STUDENTS
    (ST_ID, ST_NAME, ST_MOBILE, ST_ADDRESS)
VALUES
    (3, 'Marwa Fahim', '01248395584', '403 KFKSL');
INSERT INTO STUDENTS
    (ST_ID, ST_NAME, ST_MOBILE, ST_ADDRESS)
VALUES
    (4, 'Ayman Hesham', '01139403953', '304 JFLR');
    
INSERT INTO COURSES
    (CRS_ID, CRS_NAME, CRS_HOURS, CRS_PRICE, RND_DAYS)
VALUES
    (101, 'Java', 40, 2000, 'SUN,WED');
INSERT INTO COURSES
    (CRS_ID, CRS_NAME, CRS_HOURS, CRS_PRICE, RND_DAYS)
VALUES
    (102, 'PHP', 60, 3000, 'FRI,SAT');
INSERT INTO COURSES
    (CRS_ID, CRS_NAME, CRS_HOURS, CRS_PRICE, RND_DAYS)
VALUES
    (103, 'Oracle', 80, 5000, 'THU,WED');
    

